# general settings
name: stage1
model_type: VQGANModel
num_gpu: 4
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: facevar
    type: FaceVarDataset
    lq_folder: /mmlabworkspace_new/WorkSpaces/ngaptb/khanhnhm/khanhngo/VideoRestoration/VideoRestoration/dataset/TalkingHead/new_data/degradation/degraded_images
    gt_folder: /mmlabworkspace_new/WorkSpaces/ngaptb/khanhnhm/khanhngo/VideoRestoration/VideoRestoration/dataset/TalkingHead/new_data/degradation/images
    split_file: /mmlabworkspace_new/WorkSpaces/ngaptb/HumanActionMimic/STERRGAN/BFVR-STC/data/train_list.txt
    component_file: /mmlabworkspace_new/WorkSpaces/ngaptb/khanhnhm/khanhngo/VideoRestoration/VideoRestoration/STERR-GAN/data/train_video.json
    in_size: 256
    gt_size: 256
    # data loader
    num_worker_per_gpu: 0
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: 1
  
  val:
    name: facevar
    type: FaceVarDataset
    lq_folder: /mmlabworkspace_new/WorkSpaces/ngaptb/khanhnhm/khanhngo/VideoRestoration/VideoRestoration/dataset/TalkingHead/new_data/degradation/degraded_images
    gt_folder: /mmlabworkspace_new/WorkSpaces/ngaptb/khanhnhm/khanhngo/VideoRestoration/VideoRestoration/dataset/TalkingHead/new_data/degradation/images
    split_file: /mmlabworkspace_new/WorkSpaces/ngaptb/HumanActionMimic/STERRGAN/BFVR-STC/data/test_list.txt
    component_file: /mmlabworkspace_new/WorkSpaces/ngaptb/khanhnhm/khanhngo/VideoRestoration/VideoRestoration/STERR-GAN/data/test_video.json
    in_size: 256
    gt_size: 256
    # data loader
    num_worker_per_gpu: 0
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: 1


# network structures
network_g:
  type: VQAutoEncoder3D
  img_size: 256
  nf: 32
  ch_mult: [1, 2, 4, 8]
  quantizer: 'nearest'
  codebook_size: 1024
  model_path: "/mmlabworkspace_new/WorkSpaces/ngaptb/HumanActionMimic/STERRGAN/BFVR-STC/weights/STC/ckpt-bfvr.pth"
  stage: 1

network_d:
  type: VQGANDiscriminator3D
  nc: 3
  ndf: 32

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 7e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 7e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000]
    restart_weights: [1]
    eta_min: !!float 6e-5 # no lr reduce in official vqgan code

  total_iter: 500000

  warmup_iter: -1  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: !!float 0.5 # adaptive_weighting

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 2001
  manual_seed: 42

# validation settings
val:
  val_freq: !!float 10000 # no validation
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 10000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: gloo
  port: 29414

find_unused_parameters: true
